import {describe,expect,it} from "vitest";
import {frontmatterDelimiterLines,parseRawPrompt} from "../src/logic/importParser";
import {parseCanonicalMarkdown} from "../src/logic/canonicalMarkdownParser";
import {serializeCanonicalMarkdown} from "../src/logic/canonicalMarkdownSerializer";
import {serializeSunoPrompt,serializeSunoStyle} from "../src/logic/sunoSerializer";
import {validatePrompt} from "../src/logic/promptValidator";
import {createSequentialIdFactory} from "../src/utilities/identifiers";
const parse=(s:string)=>parseRawPrompt(s,{title:"Test",idFactory:createSequentialIdFactory()});
describe("parser edge cases",()=>{it("normalizes endings, ignores marker, and retains duplicates",()=>{const d=parse("[Intro]\r\n[same]\r\n[same]\r\n///");expect(d.sections[0]?.lines.map(x=>x.text)).toEqual(["same","same"]);});it("preserves uncertain, plain, and malformed bracket lines",()=>{const d=parse("plain\n[broken\n[No climax]");expect(d.preamble.map(x=>x.text)).toEqual(["plain","broken","No climax"]);});it("recognizes Markdown sections and lists",()=>{const d=parse("## Bridge\n- drums mute");expect(d.sections[0]?.label).toBe("Bridge");expect(d.sections[0]?.lines[0]?.text).toBe("drums mute");});it("rejects malformed canonical YAML",()=>expect(()=>parseCanonicalMarkdown("---\nprompt-grid: true\nmalformed yaml\n---\n# X")).toThrow(/Malformed/));});
describe("round trip, export, and validation",()=>{it("round trips disabled state and omits disabled lines",()=>{const d=parse("[Intro]\n[line]");d.instrumental=false;d.sections[0]!.lines[0]!.enabled=false;const md=serializeCanonicalMarkdown(d),re=parseCanonicalMarkdown(md);expect(re.sections[0]!.lines[0]!.enabled).toBe(false);expect(serializeSunoPrompt(re).output).toBe("[Intro]\n");});it("prepends Instrumental when enabled",()=>{const d=parse("[Intro]\n[line]");expect(serializeSunoPrompt(d).output).toBe("[Instrumental]\n\n[Intro]\n[line]\n");expect(serializeCanonicalMarkdown(d)).toContain("instrumental: true");});it("does not prepend Instrumental when disabled",()=>{const d=parseRawPrompt("[Intro]\n[line]",{title:"Test",instrumental:false,idFactory:createSequentialIdFactory()});expect(serializeSunoPrompt(d).output).toBe("[Intro]\n[line]\n");expect(parseCanonicalMarkdown(serializeCanonicalMarkdown(d)).instrumental).toBe(false);});it("uses the supplied default for canonical notes missing instrumental",()=>{const legacy=serializeCanonicalMarkdown(parse("[Intro]\n[line]")).replace(/^instrumental: true\n/m,"");expect(parseCanonicalMarkdown(legacy).instrumental).toBe(true);expect(parseCanonicalMarkdown(legacy,false).instrumental).toBe(false);});it("copies style alone as plain comma-separated text",()=>{const d=parse("Styles: House, Tape Soul\n[Intro]\n[line]");expect(serializeSunoStyle(d)).toBe("House, Tape Soul");expect(serializeSunoStyle(d)).not.toContain("[");});it("excludes style and musical metadata from prompt export",()=>{const d=parse("Styles: House, Tape Soul\n122 BPM • G Minor\n[Intro]\n[line]");const output=serializeSunoPrompt(d).output;expect(output).toBe("[Instrumental]\n\n[Intro]\n[line]\n");expect(output).not.toContain("House");expect(output).not.toContain("BPM");expect(output).not.toContain("Minor");});it("detects invalid BPM, duplicate IDs, empty values, and no instructions",()=>{const d=parse("");d.bpm=-1;d.title="";d.sections=[{id:"x",label:"",lines:[]},{id:"x",label:"B",lines:[]}];const codes=validatePrompt(d).map(x=>x.code);expect(codes).toEqual(expect.arrayContaining(["missing-title","invalid-bpm","empty-section-label","duplicate-id","no-instructions"]));});it("warns rather than truncating long output",()=>{const d=parse("x".repeat(20));const result=serializeSunoPrompt(d,10);expect(result.output).toContain("x".repeat(20));expect(result.warnings.some(x=>x.code==="character-threshold")).toBe(true);});});

describe("front-matter delimiter presentation",()=>{
 it("filters only paired front-matter delimiter lines",()=>{expect([...frontmatterDelimiterLines(["","---","Styles: House","---","body --- text"])]).toEqual([1,3]);expect([...frontmatterDelimiterLines(["context","---","more"])]).toEqual([]);const d=parse("---\nStyles: House\n---\nglobal context\n[Intro]\nline with --- inside");expect(d.preamble.map(x=>x.text)).toEqual(["global context"]);expect(d.sections[0]?.lines.map(x=>x.text)).toEqual(["line with --- inside"]);});
 it("round trips canonical delimiters without creating cards",()=>{const canonical=serializeCanonicalMarkdown(parse("[Intro]\n[line with --- inside]"));expect(canonical.match(/^---$/gm)).toHaveLength(2);const reparsed=parseCanonicalMarkdown(canonical);expect(reparsed.preamble.some(line=>line.text==="---")).toBe(false);expect(serializeCanonicalMarkdown(reparsed)).toBe(canonical);});
});
