import {ItemView,Notice,TFile,WorkspaceLeaf,type ViewStateResult} from "obsidian";
import type {PromptDocument,PromptGridSettings} from "../data/promptTypes";
import {PromptRepository} from "../data/promptRepository";
import {isCanonicalMarkdown,parseCanonicalMarkdown} from "../logic/canonicalMarkdownParser";
import {serializeSunoPrompt,serializeSunoStyle} from "../logic/sunoSerializer";
import {addLine,addSection,clonePrompt,deleteLine,deleteSection,editLine,editMetadata,moveLine,renameSection,reorderSection,setLineEnabled,type LineContainerId} from "../logic/promptEditor";
import {createUniqueIdFactory} from "../utilities/identifiers";
import {MetadataEditor} from "./MetadataEditor";
import {PromptSectionColumn,type SectionActions} from "./PromptSectionColumn";

export const PROMPT_GRID_VIEW_TYPE="prompt-grid-visual-composer";
type DragState={kind:"section";id:string}|{kind:"line";container:LineContainerId;id:string}|null;

export class PromptGridView extends ItemView {
 private file:TFile|null=null;private document:PromptDocument|null=null;private drag:DragState=null;private saving=false;
 constructor(leaf:WorkspaceLeaf,private readonly repository:PromptRepository,private readonly settings:()=>PromptGridSettings){super(leaf);}
 getViewType():string{return PROMPT_GRID_VIEW_TYPE;}getDisplayText():string{return this.document?.title??"Prompt Grid";}getIcon():string{return "layout-grid";}
 async onOpen():Promise<void>{this.registerEvent(this.app.vault.on("modify",file=>{if(file instanceof TFile&&file.path===this.file?.path&&!this.saving)void this.load(file);}));this.registerEvent(this.app.workspace.on("active-leaf-change",()=>{const file=this.app.workspace.getActiveFile();if(file&&file.path!==this.file?.path)void this.load(file);}));this.renderState("Open a canonical Prompt Grid note to begin.");}
 async setState(state:Record<string,unknown>,result:ViewStateResult):Promise<void>{await super.setState(state,result);const path=typeof state.filePath==="string"?state.filePath:null,found=path?this.app.vault.getAbstractFileByPath(path):null;if(found instanceof TFile)await this.load(found);else this.renderState("The requested Prompt Grid note could not be found.",true);}
 getState():Record<string,unknown>{return this.file?{filePath:this.file.path}:{};}
 async load(file:TFile):Promise<void>{this.file=file;if(file.extension!=="md"){this.document=null;this.renderState("Visual Composer requires a Markdown note.",true);return;}try{const markdown=await this.app.vault.read(file);if(!isCanonicalMarkdown(markdown)){this.document=null;this.renderState("This note is not canonical Prompt Grid Markdown.",true);return;}this.document=parseCanonicalMarkdown(markdown,this.settings().prependInstrumental);this.render();}catch(error){this.document=null;this.renderState(`Unable to open prompt: ${message(error)}`,true);}}

 private renderState(text:string,error=false):void{this.contentEl.empty();this.contentEl.createDiv({text,cls:`prompt-grid-state${error?" is-error":""}`});}
 private render():void {const document=this.document;if(!document)return;this.contentEl.empty();this.contentEl.addClass("prompt-grid-view");const toolbar=this.contentEl.createDiv({cls:"prompt-grid-toolbar"});toolbar.createEl("strong",{text:document.title});const count=toolbar.createSpan({cls:"prompt-grid-count",text:`${serializeSunoPrompt(document,this.settings().characterWarningThreshold).characterCount} characters`});this.toolbarButton(toolbar,"Copy Style",async()=>this.copy(serializeSunoStyle(document),"Style copied for Suno."));this.toolbarButton(toolbar,"Copy Prompt",async()=>this.copy(serializeSunoPrompt(document,this.settings().characterWarningThreshold).output,"Prompt copied for Suno."));this.toolbarButton(toolbar,"+ Section",async()=>{const label=window.prompt("Section name");if(label!==null)await this.mutate(d=>{addSection(d,label,createUniqueIdFactory());});});new MetadataEditor(this.contentEl.createDiv(),patch=>this.mutate(d=>editMetadata(d,patch))).render(document);count.setText(`${serializeSunoPrompt(document,this.settings().characterWarningThreshold).characterCount} characters`);const grid=this.contentEl.createDiv({cls:"prompt-grid-columns"}),actions=this.actions();const column=new PromptSectionColumn(actions);column.render(grid,null,document.preamble,-1);document.sections.forEach((section,index)=>column.render(grid,section,section.lines,index));}
 private actions():SectionActions{return {rename:(id,label)=>this.mutate(d=>renameSection(d,id,label)),remove:async id=>{const section=this.document?.sections.find(x=>x.id===id);if(section&&window.confirm(`Delete “${section.label}” and its ${section.lines.length} card(s)?`))await this.mutate(d=>deleteSection(d,id));},addLine:async container=>{const text=window.prompt("Prompt line");if(text!==null)await this.mutate(d=>{addLine(d,container,text,createUniqueIdFactory());});},move:(id,direction)=>this.mutate(d=>{const index=d.sections.findIndex(x=>x.id===id),target=index+direction;if(target>=0&&target<d.sections.length)reorderSection(d,id,target);}),sectionDragStart:id=>{this.drag={kind:"section",id};},sectionDrop:async index=>{if(this.drag?.kind==="section"){const id=this.drag.id;await this.mutate(d=>reorderSection(d,id,index));this.drag=null;}},line:{edit:(container,id,text)=>this.mutate(d=>editLine(d,container,id,text)),remove:async(container,id)=>{if(window.confirm("Delete this prompt card?"))await this.mutate(d=>deleteLine(d,container,id));},toggle:(container,id,enabled)=>this.mutate(d=>setLineEnabled(d,container,id,enabled)),move:(container,id,direction)=>this.mutate(d=>{const list=container==="preamble"?d.preamble:d.sections.find(x=>x.id===container)?.lines;if(!list)return;const index=list.findIndex(x=>x.id===id),target=index+direction;if(target>=0&&target<list.length)moveLine(d,container,id,container,target);}),dragStart:(container,id)=>{this.drag={kind:"line",container,id};},drop:async(container,index)=>{if(this.drag?.kind==="line"){const source=this.drag.container,id=this.drag.id;await this.mutate(d=>moveLine(d,source,id,container,index));this.drag=null;}}}};}
 private async mutate(change:(document:PromptDocument)=>void):Promise<void>{if(!this.document||!this.file)return;const before=clonePrompt(this.document);try{change(this.document);this.document.updatedAt=new Date().toISOString();this.saving=true;await this.repository.updateCanonical(this.file,this.document);new Notice("Prompt saved.",1200);this.render();}catch(error){this.document=before;this.render();new Notice(`Prompt Grid: ${message(error)}`,6000);}finally{this.saving=false;}}
 private toolbarButton(parent:HTMLElement,label:string,action:()=>Promise<void>):void{const button=parent.createEl("button",{text:label});button.addEventListener("click",()=>void action().catch(error=>new Notice(`Prompt Grid: ${message(error)}`,6000)));}
 private async copy(text:string,notice:string):Promise<void>{await navigator.clipboard.writeText(text);new Notice(notice);}
}
function message(error:unknown):string{return error instanceof Error?error.message:String(error);}
