import {ItemView,Notice,TFile,WorkspaceLeaf,type ViewStateResult} from "obsidian";
import type {PromptDocument,PromptGridSettings} from "../data/promptTypes";
import {PromptRepository} from "../data/promptRepository";
import {isCanonicalMarkdown,parseCanonicalMarkdown} from "../logic/canonicalMarkdownParser";
import {serializeSunoPrompt,serializeSunoStyle} from "../logic/sunoSerializer";
import {addLine,addSection,clonePrompt,deleteLine,deleteSection,editLine,editMetadata,moveLine,renameSection,reorderSection,setLineEnabled,type LineContainerId} from "../logic/promptEditor";
import {createUniqueIdFactory} from "../utilities/identifiers";
import {PromptSectionColumn,type SectionActions} from "./PromptSectionColumn";
import {FloatingMenuController} from "./FloatingMenu";
import {documentChanged,instrumentalMenuChecked,planLineDrop,restoreCollapsedColumns,shouldRenderPreamble,storeCollapsedColumns} from "./composerPresentation";

export const PROMPT_GRID_VIEW_TYPE="prompt-grid-visual-composer";
type DragState={kind:"section";id:string}|{kind:"line";container:LineContainerId;id:string}|null;

export class PromptGridView extends ItemView {
 private file:TFile|null=null;private document:PromptDocument|null=null;private drag:DragState=null;private saving=false;private collapsed=new Set<string>();private focusLineId:string|null=null;private readonly menus=new FloatingMenuController();
 constructor(leaf:WorkspaceLeaf,private readonly repository:PromptRepository,private readonly settings:()=>PromptGridSettings){super(leaf);}
 getViewType():string{return PROMPT_GRID_VIEW_TYPE;}getDisplayText():string{return this.document?.title??"Prompt Grid";}getIcon():string{return "layout-grid";}
 async onOpen():Promise<void>{this.registerEvent(this.app.vault.on("modify",file=>{if(file instanceof TFile&&file.path===this.file?.path&&!this.saving)void this.loadFile(file);}));this.registerEvent(this.app.workspace.on("active-leaf-change",()=>{const file=this.app.workspace.getActiveFile();if(file&&file.path!==this.file?.path)void this.loadFile(file);}));this.renderState("Open a canonical Prompt Grid note to begin.");}
 async onClose():Promise<void>{this.menus.destroy();}
 async setState(state:Record<string,unknown>,result:ViewStateResult):Promise<void>{await super.setState(state,result);this.collapsed=restoreCollapsedColumns(state.collapsed);const path=typeof state.filePath==="string"?state.filePath:null,found=path?this.app.vault.getAbstractFileByPath(path):null;if(found instanceof TFile)await this.loadFile(found);else this.renderState("The requested Prompt Grid note could not be found.",true);}
 getState():Record<string,unknown>{return {filePath:this.file?.path,collapsed:storeCollapsedColumns(this.collapsed)};}
 async loadFile(file:TFile):Promise<void>{this.file=file;if(file.extension!=="md"){this.document=null;this.renderState("Visual Composer requires a Markdown note.",true);return;}try{const markdown=await this.app.vault.read(file);if(!isCanonicalMarkdown(markdown)){this.document=null;this.renderState("This note is not canonical Prompt Grid Markdown.",true);return;}this.document=parseCanonicalMarkdown(markdown,this.settings().prependInstrumental);this.render();}catch(error){this.document=null;this.renderState(`Unable to open prompt: ${message(error)}`,true);}}

 private renderState(text:string,error=false):void{this.menus.close();this.contentEl.empty();this.contentEl.createDiv({text,cls:`prompt-grid-state${error?" is-error":""}`});}
 private render():void {const document=this.document;if(!document)return;this.menus.close();this.contentEl.empty();this.contentEl.addClass("prompt-grid-view");const toolbar=this.contentEl.createDiv({cls:"prompt-grid-toolbar"});toolbar.createEl("strong",{text:document.title});const count=toolbar.createSpan({cls:"prompt-grid-count",text:`${serializeSunoPrompt(document,this.settings().characterWarningThreshold).characterCount} characters`});this.toolbarButton(toolbar,"Copy Style",async()=>this.copy(serializeSunoStyle(document),"Style copied for Suno."));this.toolbarButton(toolbar,"Copy Prompt",async()=>this.copy(serializeSunoPrompt(document,this.settings().characterWarningThreshold).output,"Prompt copied for Suno."));this.toolbarButton(toolbar,"+ Section",async()=>{const label=window.prompt("Section name");if(label!==null)await this.mutate(d=>{addSection(d,label,createUniqueIdFactory());});});this.boardMenu(toolbar,document);count.setText(`${serializeSunoPrompt(document,this.settings().characterWarningThreshold).characterCount} characters`);const grid=this.contentEl.createDiv({cls:"prompt-grid-columns"}),actions=this.actions(),column=new PromptSectionColumn(actions,this.menus);if(shouldRenderPreamble(document.preamble.length))column.render(grid,null,document.preamble,-1,this.collapsed.has("preamble"));document.sections.forEach((section,index)=>column.render(grid,section,section.lines,index,this.collapsed.has(section.id)));this.restoreCardFocus();}
 private actions():SectionActions{return {rename:(id,label)=>this.mutate(d=>renameSection(d,id,label)),remove:async id=>{const section=this.document?.sections.find(x=>x.id===id);if(section&&window.confirm(`Delete “${section.label}” and its ${section.lines.length} card(s)?`))await this.mutate(d=>deleteSection(d,id));},addLine:async container=>{const text=window.prompt("Prompt line");if(text!==null)await this.mutate(d=>{addLine(d,container,text,createUniqueIdFactory());});},move:(id,direction)=>{this.focusLineId=null;return this.mutate(d=>{const index=d.sections.findIndex(x=>x.id===id),target=index+direction;if(target>=0&&target<d.sections.length)reorderSection(d,id,target);});},toggleCollapse:id=>this.toggleCollapse(id),sectionDragStart:id=>{this.drag={kind:"section",id};},sectionDrop:async index=>{if(this.drag?.kind==="section"){const id=this.drag.id;await this.mutate(d=>reorderSection(d,id,index));this.drag=null;}},line:{edit:(container,id,text)=>this.mutate(d=>editLine(d,container,id,text)),remove:async(container,id)=>{if(window.confirm("Delete this prompt card?"))await this.mutate(d=>deleteLine(d,container,id));},toggle:(container,id,enabled)=>this.mutate(d=>setLineEnabled(d,container,id,enabled)),move:(container,id,direction)=>{this.focusLineId=id;return this.mutate(d=>{const list=container==="preamble"?d.preamble:d.sections.find(x=>x.id===container)?.lines;if(!list)return;const index=list.findIndex(x=>x.id===id),target=index+direction;if(target>=0&&target<list.length)moveLine(d,container,id,container,target);});},dragStart:(container,id)=>{this.drag={kind:"line",container,id};},dragEnd:()=>{this.drag=null;this.clearDropIndicators();},drop:async(container,index)=>{if(this.drag?.kind==="line"&&this.document){const source=this.drag.container,id=this.drag.id,target=planLineDrop(this.document,source,id,container,index);this.drag=null;this.clearDropIndicators();if(target!==null)await this.mutate(d=>moveLine(d,source,id,container,target));}}}};}
 private async mutate(change:(document:PromptDocument)=>void):Promise<void>{if(!this.document||!this.file)return;const before=clonePrompt(this.document);try{change(this.document);if(!documentChanged(before,this.document)){this.restoreCardFocus();return;}this.document.updatedAt=new Date().toISOString();this.saving=true;await this.repository.updateCanonical(this.file,this.document);this.render();}catch(error){this.document=before;this.render();new Notice(`Prompt Grid: ${message(error)}`,6000);}finally{this.saving=false;}}
 private toggleCollapse(id:LineContainerId):void{this.collapsed.has(id)?this.collapsed.delete(id):this.collapsed.add(id);this.app.workspace.requestSaveLayout();this.render();}
 private boardMenu(parent:HTMLElement,document:PromptDocument):void{const trigger=parent.createEl("button",{text:"…",cls:"prompt-grid-menu-trigger prompt-grid-board-menu-trigger",attr:{"aria-label":"Board actions","aria-expanded":"false"}});trigger.addEventListener("click",()=>this.menus.open(trigger,"board",[{label:"Edit title",action:async()=>{const value=window.prompt("Document title",document.title);if(value!==null)await this.mutate(d=>editMetadata(d,{title:value}));}},{label:"Edit style",action:async()=>{const value=window.prompt("Comma-separated styles",document.styles.join(", "));if(value!==null)await this.mutate(d=>editMetadata(d,{styles:value.split(",")}));}},{label:"Edit BPM",action:async()=>{const value=window.prompt("BPM (blank for none)",document.bpm===null?"":String(document.bpm));if(value!==null)await this.mutate(d=>editMetadata(d,{bpm:value.trim()?Number(value):null}));}},{label:"Edit key",action:async()=>{const value=window.prompt("Key (blank for none)",document.key??"");if(value!==null)await this.mutate(d=>editMetadata(d,{key:value}));}},{label:"Instrumental",checked:instrumentalMenuChecked(document),action:()=>this.mutate(d=>editMetadata(d,{instrumental:!document.instrumental}))},{label:"Add preamble",action:async()=>{const text=window.prompt("Preamble line");if(text!==null)await this.mutate(d=>{addLine(d,"preamble",text,createUniqueIdFactory());});}},{label:"Collapse all",action:()=>{this.collapsed=new Set([...document.sections.map(section=>section.id),...(document.preamble.length?["preamble"]:[])]);this.app.workspace.requestSaveLayout();this.render();}},{label:"Expand all",action:()=>{this.collapsed.clear();this.app.workspace.requestSaveLayout();this.render();}}]));}
 private clearDropIndicators():void{this.contentEl.querySelectorAll(".drop-before,.drop-after,.drop-at-end").forEach(element=>element.removeClasses(["drop-before","drop-after","drop-at-end"]));}
 private restoreCardFocus():void{if(!this.focusLineId)return;const id=this.focusLineId;this.focusLineId=null;(this.contentEl.querySelector(`[data-line-id="${CSS.escape(id)}"] .prompt-grid-card-text`) as HTMLElement|null)?.focus();}
 private toolbarButton(parent:HTMLElement,label:string,action:()=>Promise<void>):void{const button=parent.createEl("button",{text:label});button.addEventListener("click",()=>void action().catch(error=>new Notice(`Prompt Grid: ${message(error)}`,6000)));}
 private async copy(text:string,notice:string):Promise<void>{await navigator.clipboard.writeText(text);new Notice(notice);}
}
function message(error:unknown):string{return error instanceof Error?error.message:String(error);}
