import type {PromptLine} from "../data/promptTypes";
import type {LineContainerId} from "../logic/promptEditor";
import {resolveCardEdit} from "./composerPresentation";
import type {FloatingMenuController} from "./FloatingMenu";

export interface LineCardActions {edit:(container:LineContainerId,id:string,text:string)=>Promise<void>;remove:(container:LineContainerId,id:string)=>Promise<void>;toggle:(container:LineContainerId,id:string,enabled:boolean)=>Promise<void>;move:(container:LineContainerId,id:string,direction:-1|1)=>Promise<void>;dragStart:(container:LineContainerId,id:string)=>void;dragEnd:()=>void;drop:(container:LineContainerId,index:number)=>Promise<void>}

export class PromptLineCard {
 constructor(private readonly actions:LineCardActions,private readonly menus:FloatingMenuController){}
 render(parent:HTMLElement,line:PromptLine,containerId:LineContainerId,index:number):void {
  const card=parent.createDiv({cls:`prompt-grid-card${line.enabled?"":" is-disabled"}`,attr:{draggable:"true"}});card.dataset.lineId=line.id;
  const clearDragBlock=()=>delete card.dataset.dragBlocked;card.addEventListener("pointerdown",event=>{card.dataset.dragBlocked=String(Boolean((event.target as HTMLElement|null)?.closest(".prompt-grid-card-text, textarea, details, summary, button")));});card.addEventListener("pointerup",clearDragBlock);card.addEventListener("pointercancel",clearDragBlock);card.addEventListener("dragstart",event=>this.dragStart(event,card,containerId,line.id));card.addEventListener("dragend",()=>{card.removeClasses(["is-dragging","drop-before","drop-after"]);this.actions.dragEnd();});
  card.addEventListener("dragover",event=>{event.preventDefault();event.stopPropagation();const after=event.clientY>card.getBoundingClientRect().top+card.offsetHeight/2;card.toggleClass("drop-before",!after);card.toggleClass("drop-after",after);});
  card.addEventListener("dragleave",event=>{if(!card.contains(event.relatedTarget as Node|null))card.removeClasses(["drop-before","drop-after"]);});
  card.addEventListener("drop",event=>{event.preventDefault();event.stopPropagation();const after=card.hasClass("drop-after");card.removeClasses(["drop-before","drop-after"]);void this.actions.drop(containerId,index+(after?1:0));});
  const row=card.createDiv({cls:"prompt-grid-card-row"}),text=row.createDiv({text:line.text,cls:"prompt-grid-card-text",attr:{tabindex:"0","aria-label":"Edit prompt card"}});
  text.addEventListener("dblclick",()=>this.edit(card,row,text,line,containerId,selectionWithin(text)));text.addEventListener("keydown",event=>{if(event.key==="Enter"){event.preventDefault();this.edit(card,row,text,line,containerId);}});card.addEventListener("contextmenu",event=>{event.preventDefault();this.contextMenu(text,line,containerId);});
 }
 private dragStart(event:DragEvent,card:HTMLElement,containerId:LineContainerId,id:string):void {const target=event.target as HTMLElement|null,selection=window.getSelection();if(card.hasClass("is-editing")||card.dataset.dragBlocked==="true"||target?.closest(".prompt-grid-card-text, textarea, details, summary, button")||(selection&&!selection.isCollapsed&&selection.anchorNode&&card.contains(selection.anchorNode))){event.preventDefault();return;}event.dataTransfer?.setData("text/plain",id);event.dataTransfer?.setDragImage(card,12,12);card.addClass("is-dragging");this.actions.dragStart(containerId,id);}
 private edit(card:HTMLElement,row:HTMLElement,text:HTMLElement,line:PromptLine,containerId:LineContainerId,selection?:[number,number]):void {if(card.hasClass("is-editing"))return;card.addClass("is-editing");card.draggable=false;text.hide();const editor=row.createEl("textarea",{cls:"prompt-grid-card-editor",attr:{"aria-label":"Edit prompt card"}});editor.value=line.text;editor.style.height=`${Math.max(text.offsetHeight,24)}px`;const resize=()=>{editor.style.height="auto";editor.style.height=`${Math.max(text.offsetHeight,editor.scrollHeight)}px`;};editor.focus();const [start,end]=selection??[editor.value.length,editor.value.length];editor.setSelectionRange(start,end);let finished=false;const finish=(commit:boolean)=>{if(finished)return;finished=true;const value=resolveCardEdit(line.text,editor.value,commit);if(value!==null)void this.actions.edit(containerId,line.id,value);else{editor.remove();text.show();card.removeClass("is-editing");card.draggable=true;}};editor.addEventListener("input",resize);editor.addEventListener("blur",()=>finish(true));editor.addEventListener("keydown",event=>{if(event.key==="Escape"){event.preventDefault();finish(false);}else if(event.key==="Enter"&&(event.metaKey||event.ctrlKey)){event.preventDefault();finish(true);}});}
 private contextMenu(trigger:HTMLElement,line:PromptLine,containerId:LineContainerId):void {this.menus.open(trigger,`line:${line.id}`,[{label:"Enabled",checked:line.enabled,action:()=>this.actions.toggle(containerId,line.id,!line.enabled)},{label:"Delete",danger:true,action:()=>this.actions.remove(containerId,line.id)}]);}
}

function selectionWithin(element:HTMLElement):[number,number]|undefined {const selection=window.getSelection();if(!selection||selection.rangeCount===0||!selection.anchorNode||!element.contains(selection.anchorNode))return undefined;return [Math.min(selection.anchorOffset,selection.focusOffset),Math.max(selection.anchorOffset,selection.focusOffset)];}
