import type {PromptDocument,PromptLine,PromptSection} from "../data/promptTypes";
import {createUniqueIdFactory,type IdFactory} from "../utilities/identifiers";
import {normalizeLineEndings} from "../utilities/textNormalization";
import {parseMetadataLine} from "./metadataParser";
import {isSectionLabel} from "./sectionClassifier";
export interface ParseOptions {title?:string;sourcePath?:string|null;preserveSource?:boolean;instrumental?:boolean;idFactory?:IdFactory;now?:string}
type Item={text:string;definiteSection:boolean;bracketed:boolean};
export function parseRawPrompt(input:string,options:ParseOptions={}):PromptDocument { const ids=options.idFactory??createUniqueIdFactory(), now=options.now??new Date().toISOString(); let styles:string[]=[],bpm:number|null=null,key:string|null=null; const items:Item[]=[]; for(const raw of normalizeLineEndings(input).split("\n")){const t=raw.trim();if(!t||t==="///")continue;const meta=parseMetadataLine(t);if(meta.consumed){if(meta.styles.length)styles=meta.styles;if(meta.bpm!==null)bpm=meta.bpm;if(meta.key!==null)key=meta.key;continue;} const heading=/^##\s+(.+?)(?:\s+\{#[^}]+\})?$/.exec(t);if(heading){items.push({text:heading[1]!.trim(),definiteSection:true,bracketed:false});continue;} const list=/^-\s+(?:\[[^\]]+\]\s*)?(.*)$/.exec(t);if(list){if(list[1]!.trim())items.push({text:list[1]!.trim(),definiteSection:false,bracketed:false});continue;} const bracket=/^\[(.*)\]$/.exec(t);if(bracket){if(bracket[1]!.trim())items.push({text:bracket[1]!.trim(),definiteSection:false,bracketed:true});continue;} items.push({text:t.startsWith("[")?t.slice(1).trim():t,definiteSection:false,bracketed:false});}
 const preamble:PromptLine[]=[],sections:PromptSection[]=[];let current:PromptSection|null=null; const line=(text:string):PromptLine=>({id:ids.line(),text,enabled:true}); for(let i=0;i<items.length;i++){const item=items[i]!;const followed=i+1<items.length;const section=item.definiteSection||(item.bracketed&&isSectionLabel(item.text,followed));if(section){current={id:ids.section(),label:item.text,lines:[]};sections.push(current);}else (current?.lines??preamble).push(line(item.text));}
 return {id:ids.prompt(),title:options.title?.trim()||"Untitled Prompt",styles,bpm,key,instrumental:options.instrumental??true,extraFrontmatter:{status:"inbox"},preamble,sections,sourcePath:options.sourcePath??null,sourceText:options.preserveSource===false?null:input,createdAt:now,updatedAt:now}; }
