import {Notice,Plugin,TFile} from "obsidian";
import type {PromptDocument,PromptGridSettings} from "./data/promptTypes";
import {PromptRepository,openFile} from "./data/promptRepository";
import {parseRawPrompt} from "./logic/importParser";
import {isCanonicalMarkdown,parseCanonicalMarkdown} from "./logic/canonicalMarkdownParser";
import {serializeSunoPrompt,serializeSunoStyle} from "./logic/sunoSerializer";
import {validatePrompt} from "./logic/promptValidator";
import {createUniqueIdFactory} from "./utilities/identifiers";
import {titleFromName} from "./utilities/fileNaming";
import {choosePromptFile} from "./interface/ImportFileModal";
import {PromptGridSettingsTab} from "./interface/PromptGridSettingsTab";
const DEFAULTS:PromptGridSettings={inboxFolder:"Prompts/Inbox",exportFolder:"Prompts/Exports",defaultTitlePrefix:"Prompt",characterWarningThreshold:3000,preserveSourceText:true,prependInstrumental:true};
export default class PromptGridPlugin extends Plugin {settings:PromptGridSettings=DEFAULTS;private repository!:PromptRepository;async onload():Promise<void>{await this.loadSettings();this.repository=new PromptRepository(this.app.vault);this.addSettingTab(new PromptGridSettingsTab(this.app,this));this.addCommand({id:"import-clipboard",name:"Import from clipboard",callback:()=>void this.guard(async()=>this.importRaw(await navigator.clipboard.readText(),`${this.settings.defaultTitlePrefix} ${new Date().toISOString().slice(0,10)}`))});this.addCommand({id:"import-markdown-file",name:"Import Markdown file",callback:()=>void this.guard(async()=>{const file=await choosePromptFile();if(file)await this.importRaw(await file.text(),titleFromName(file.name),file.name);})});this.addCommand({id:"convert-current-note",name:"Convert current note",callback:()=>void this.guard(async()=>{const {file,text}=await this.active();if(isCanonicalMarkdown(text)){this.showValidation(parseCanonicalMarkdown(text,this.settings.prependInstrumental));return;}await this.importRaw(text,titleFromName(file.name),file.path);})});this.addCommand({id:"copy-current-note-suno",name:"Copy current note for Suno",callback:()=>void this.guard(async()=>{const d=await this.activeCanonical();const errors=validatePrompt(d,this.settings.characterWarningThreshold).filter(x=>x.severity==="error");if(errors.length)throw new Error(errors.map(x=>x.message).join("; "));const result=serializeSunoPrompt(d,this.settings.characterWarningThreshold);await navigator.clipboard.writeText(result.output);new Notice(`Copied ${result.characterCount} prompt characters for Suno.`);})});this.addCommand({id:"copy-style-suno",name:"Copy Style for Suno",callback:()=>void this.guard(async()=>{const style=serializeSunoStyle(await this.activeCanonical());await navigator.clipboard.writeText(style);new Notice(`Copied ${style.length} style characters for Suno.`);})});this.addCommand({id:"export-current-note-suno",name:"Export current note for Suno",callback:()=>void this.guard(async()=>{const result=await this.repository.exportSuno(await this.activeCanonical(),this.settings.exportFolder);new Notice(`Exported ${result.file.path} (${result.characterCount} characters).`);})});this.addCommand({id:"validate-current-note",name:"Validate current note",callback:()=>void this.guard(async()=>this.showValidation(await this.activeCanonical()))});}
 async loadSettings():Promise<void>{this.settings=Object.assign({},DEFAULTS,await this.loadData() as Partial<PromptGridSettings>);}async saveSettings():Promise<void>{await this.saveData(this.settings);}private async active():Promise<{file:TFile;text:string}>{const file=this.app.workspace.getActiveFile();if(!(file instanceof TFile)||file.extension!=="md")throw new Error("No active Markdown note.");return {file,text:await this.app.vault.read(file)};}private async activeCanonical():Promise<PromptDocument>{const {text}=await this.active();if(!isCanonicalMarkdown(text))throw new Error("The active note is not canonical Prompt Grid Markdown.");return parseCanonicalMarkdown(text,this.settings.prependInstrumental);}private async importRaw(text:string,title:string,sourcePath:string|null=null):Promise<void>{if(!text.trim())throw new Error("The import is empty.");const d=parseRawPrompt(text,{title,sourcePath,preserveSource:this.settings.preserveSourceText,instrumental:this.settings.prependInstrumental,idFactory:createUniqueIdFactory()});const file=await this.repository.saveCanonical(d,this.settings.inboxFolder);await openFile(this.app,file);new Notice(`Imported ${file.path}.`);}private showValidation(d:PromptDocument):void{const issues=validatePrompt(d,this.settings.characterWarningThreshold);new Notice(issues.length?issues.map(x=>`${x.severity}: ${x.message}`).join("\n"):"Prompt is valid.",8000);}private async guard(action:()=>Promise<void>):Promise<void>{try{await action();}catch(e){console.error("Prompt Grid",e);new Notice(`Prompt Grid: ${e instanceof Error?e.message:String(e)}`,8000);}}}
export {parseRawPrompt} from "./logic/importParser";
export {parseCanonicalMarkdown} from "./logic/canonicalMarkdownParser";
export {serializeCanonicalMarkdown} from "./logic/canonicalMarkdownSerializer";
export {serializeSunoPrompt} from "./logic/sunoSerializer";
export {serializeSunoStyle} from "./logic/sunoSerializer";
export {validatePrompt} from "./logic/promptValidator";
